### PR TITLE
Allow to set custom memory size.

### PR DESCRIPTION
**Pull request by IvanGoncharov**
At the moment, memory size is only 16mb so lib crash on big graphs with the following error:
```
Uncaught abort("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which adjusts the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ") at Error
```

So this PR add `setMemorySize` function to force bigger memory size, for e.g. we set it to 32mb in our project.

### CODE REVIEW

**Comment by mdaines** [comment]
Looks good, thanks!

**Comment by IvanGoncharov** [comment]
@mdaines Thank you. Happy new year 🎄 
Can you please publish the new version of npm package?

**Comment by mdaines** [comment]
Yes, I plan to publish a new version in the next week or so.

**Comment by mdaines** [comment]
Just a note that I've gone with a different approach: Viz.js will now set ALLOW_MEMORY_GROWTH, so you don't have to guess the amount of memory it needs. b1df4a9662188fb1aefb0489ae6f1c4667bec81f

**Pull request merged**
