### PR TITLE
Export class Viz

### PR DESCRIPTION
**Pull request by mfbx9da4**

### CODE REVIEW

**Comment by mdaines** [comment]
Can you provide an explanation of this change? What does adding the export keyword accomplish?

Also, does this change the results of the type tests? https://github.com/mdaines/viz-js/blob/3ef0b7f41d315d52048e6c6246d054b62b8d3017/packages/viz/test/types/top-level.ts

The `Viz` class is not exported in JavaScript, so the desired effect of the declaration file is to provide the type information but not declare that the class itself is available directly.

**Comment by mfbx9da4** [comment]
Hi I was passing around the `Viz` instance eg

```typescript
function visualize(viz: Viz) {
  // ...
}
```

Since it wasn't exported I couldn't reference the type. I think it's obvious enough to the user they can't construct the `Viz` class themselves. You could make it even clearer by adding the following:

```typescript
class Viz {
  /** Cannot construct `Viz` class directly use `instance()` instead */
  private constructor() {
    throw new Error("Cannot construct `Viz` class directly use `instance()` instead");
  }
}
```

That way `new Viz()` will always throw a typescript error and tell them what to do instead.

Regarding the tests, yes, likely those tests will now fail.

**Comment by mdaines** [comment]
That seems like it should work, but I don't want to just hide the constructor and leave the class in the declaration because that doesn't match what happens in JavaScript. I do want to be able to reference `Viz` for typechecking, though.

It looks like this can be done with the type modifier, but I'll need to add a type export. See #225.

```ts
import { instance, type Viz } from "@viz-js/viz";

function myRender(viz: Viz, src: string) {
  return viz.render(src);
}

instance().then(viz => {
  myRender(viz, "digraph { a -> b }");
});
```

I'm also going to enable the [verbatimModuleSyntax](https://www.typescriptlang.org/tsconfig#verbatimModuleSyntax) flag in the type tests.

**Comment by mdaines** [comment]
I'm closing this in favor of #225. Thank you for pointing this out.

**Pull request closed without merging**
