### PR TITLE
Add pan & zoom to SVG and resizable panes

### PR DESCRIPTION
**Pull request by patrickpilch**
Hi, thanks for your work on viz.js. I think that your website is the best GUI tool I've used for GraphViz so far, and significantly sped up my edit and test cycle.

But the two features I found myself longing for were re-sizable panes (to leverage a large display) and pan & zoom with the SVG output container (to inspect sub-areas of large renders.)

I thought I'd whip up a quick PR to add them!

### CODE REVIEW

**Comment by mdaines** [comment]
I think this looks good, but can you include the dependencies with Bower?

**Comment by patrickpilch** [comment]
@mdaines updated

**Comment by mdaines** [comment]
@patrickpilch The split view looks good, but I notice that when resizing the window, the svg-pan-zoom controls don't adjust to the new size of the graph pane. We probably want something like this: http://ariutta.github.io/svg-pan-zoom/demo/resize.html -- although ideally without bringing jQuery in as well.

**Comment by patrickpilch** [comment]
@mdaines updated. It may be worth considering adding something like jQuery or Lodash to avoid rewriting lots of common code like debouncing.

**Comment by mdaines** [comment]
Merged. Thanks!

**Pull request merged**
